[2023-12-26T08:40:19.186+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sensor_target_dag.waiting_end_parent_dag scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T08:40:19.195+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sensor_target_dag.waiting_end_parent_dag scheduled__2023-12-25T00:00:00+00:00 [queued]>
[2023-12-26T08:40:19.195+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:40:19.195+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-26T08:40:19.195+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T08:40:19.214+0000] {taskinstance.py:1383} INFO - Executing <Task(ExternalTaskSensor): waiting_end_parent_dag> on 2023-12-25 00:00:00+00:00
[2023-12-26T08:40:19.220+0000] {standard_task_runner.py:55} INFO - Started process 1767 to run task
[2023-12-26T08:40:19.223+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sensor_target_dag', 'waiting_end_parent_dag', 'scheduled__2023-12-25T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/sensor_target_dag.py', '--cfg-path', '/tmp/tmpzaq_qrjq']
[2023-12-26T08:40:19.223+0000] {standard_task_runner.py:83} INFO - Job 164: Subtask waiting_end_parent_dag
[2023-12-26T08:40:19.240+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:549: DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-12-26T08:40:19.284+0000] {task_command.py:376} INFO - Running <TaskInstance: sensor_target_dag.waiting_end_parent_dag scheduled__2023-12-25T00:00:00+00:00 [running]> on host d2fc15a9183d
[2023-12-26T08:40:19.322+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:549: DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
  option = self._get_option_from_config_file(deprecated_key, deprecated_section, key, kwargs, section)

[2023-12-26T08:40:19.364+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sensor_target_dag
AIRFLOW_CTX_TASK_ID=waiting_end_parent_dag
AIRFLOW_CTX_EXECUTION_DATE=2023-12-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-25T00:00:00+00:00
[2023-12-26T08:40:19.365+0000] {external_task.py:206} INFO - Poking for tasks ['end'] in dag sensor_parent_dag on 2023-12-25T00:00:00+00:00 ... 
[2023-12-26T08:41:19.434+0000] {external_task.py:206} INFO - Poking for tasks ['end'] in dag sensor_parent_dag on 2023-12-25T00:00:00+00:00 ... 
[2023-12-26T08:41:45.221+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to None. Terminating instance.
[2023-12-26T08:41:45.224+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1767. PIDs of all processes in the group: [1767]
[2023-12-26T08:41:45.225+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1767
[2023-12-26T08:41:45.225+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-26T08:41:45.238+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 211, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1564, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-12-26T08:41:45.248+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=sensor_target_dag, task_id=waiting_end_parent_dag, execution_date=20231225T000000, start_date=20231226T084019, end_date=20231226T084145
[2023-12-26T08:41:45.264+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 164 for task waiting_end_parent_dag ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(sensor_target_dag, waiting_end_parent_dag, scheduled__2023-12-25T00:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'waiting_end_parent_dag', 'dag_id': 'sensor_target_dag', 'run_id': 'scheduled__2023-12-25T00:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2023, 12, 26, 8, 40, 19, 187094, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 12, 26, 8, 41, 45, 247681, tzinfo=Timezone('UTC')), 'duration': 86}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1767)
[2023-12-26T08:41:45.281+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1767, status='terminated', exitcode=1, started='08:40:18') (1767) terminated with exit code 1
